"""
Pipeline Orchestrator Agent

Main orchestrator agent that manages the entire document processing pipeline
using LangGraph. Replaces the Event-Driven architecture with a unified agent
that has full visibility and control over all stages.

Features:
- State management with checkpoints (recovery on crash)
- Legacy data validation (reads old data, compares with new, merges)
- Observability (persists events at each stage)
- Intelligent decisions (based on previous results)
- Sub-agents as tools (ValidationService, OCRService, SegmentationAgent, etc.)

Related: REQ-027_ORCHESTRATOR_MIGRATION.md, AGENT_ORCHESTRATION_ARCHITECTURE.md
Date: 2026-04-10
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import time
import traceback
from datetime import datetime
from typing import TypedDict, Optional, Dict, Any, List, Literal
from uuid import UUID

from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver

from adapters.driven.persistence.migration_models import (
    PipelineStage,
    LegacyData,
    NewData,
    ValidationResult,
    MergedData,
    DataSource
)
from adapters.driven.persistence.legacy_data_repository import LegacyDataRepository

logger = logging.getLogger(__name__)


# ============================================================================
# State Definition
# ============================================================================

class OrchestratorState(TypedDict):
    """
    Shared state for the entire pipeline orchestrator.
    
    This state is passed between all nodes and provides:
    - Full visibility of all previous results
    - Context for intelligent decisions
    - Legacy data for validation
    - Events for observability
    """
    # Document info
    document_id: str
    filename: str
    filepath: str
    
    # Metadata (extracted from filename or legacy)
    metadata: Dict[str, Any]  # {publication_date, newspaper, sha8, etc.}
    
    # Pipeline context (results from each stage)
    pipeline_context: Dict[str, Any]  # {ocr: {...}, segmentation: {...}, etc.}
    
    # Current stage tracking
    current_stage: Optional[str]
    
    # Migration mode (True if document is legacy)
    migration_mode: bool
    
    # Legacy data (for validation)
    legacy_data: Dict[str, Any]  # {stage: LegacyData}
    
    # New data (generated by orchestrator)
    new_data: Dict[str, Any]  # {stage: NewData}
    
    # Validation results (legacy vs new)
    validation_results: Dict[str, Any]  # {stage: ValidationResult}
    
    # Merged data (final result)
    merged_data: Dict[str, Any]  # {stage: MergedData}
    
    # Events timeline (for observability)
    events: List[Dict[str, Any]]
    
    # Errors encountered
    errors: List[Dict[str, Any]]
    
    # Flags for flow control
    skip_insights: bool
    retry_ocr_with_tika: bool


# ============================================================================
# Helper Functions
# ============================================================================

async def _persist_event(
    document_id: str,
    stage: str,
    status: str,
    duration: Optional[float] = None,
    metadata: Optional[Dict[str, Any]] = None,
    error_type: Optional[str] = None,
    error_message: Optional[str] = None,
    error_detail: Optional[Dict[str, Any]] = None,
    result_ref: Optional[str] = None,
    result_size_bytes: Optional[int] = None,
    db_pool = None
):
    """
    Persist pipeline event to document_processing_log.
    Called by orchestrator after each stage.
    """
    if db_pool is None:
        logger.warning(f"No DB pool provided, cannot persist event: {document_id}/{stage}")
        return
    
    try:
        await db_pool.execute(
            """
            INSERT INTO document_processing_log 
            (document_id, stage, status, duration_sec, metadata, 
             error_type, error_message, error_detail, result_ref, result_size_bytes, event_source)
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'orchestrator')
            """,
            document_id,
            stage,
            status,
            duration,
            metadata,
            error_type,
            error_message,
            error_detail,
            result_ref,
            result_size_bytes
        )
        logger.debug(f"Event persisted: {document_id}/{stage}/{status}")
    except Exception as e:
        logger.error(f"Failed to persist event: {e}")


# ============================================================================
# Orchestrator Nodes
# ============================================================================

async def check_if_legacy_node(state: OrchestratorState, db_pool) -> OrchestratorState:
    """
    Entry node: Check if document is legacy (needs migration validation).
    """
    document_id = state['document_id']
    
    try:
        # Query document_status to check data_source
        row = await db_pool.fetchrow(
            """
            SELECT data_source, migration_status, publication_date, newspaper_name, sha8_prefix
            FROM document_status
            WHERE document_id = $1
            """,
            document_id
        )
        
        if not row:
            logger.warning(f"Document not found in DB: {document_id}")
            state['migration_mode'] = False
            return state
        
        # Set migration mode
        state['migration_mode'] = (row['data_source'] == 'legacy')
        
        # Load metadata
        state['metadata'] = {
            'publication_date': row['publication_date'].isoformat() if row['publication_date'] else None,
            'newspaper': row['newspaper_name'],
            'sha8': row['sha8_prefix'],
            'data_source': row['data_source'],
            'migration_status': row['migration_status']
        }
        
        logger.info(
            f"Document {document_id}: migration_mode={state['migration_mode']}, "
            f"source={row['data_source']}, newspaper={row['newspaper_name']}"
        )
        
    except Exception as e:
        logger.error(f"Error checking legacy status: {e}")
        state['migration_mode'] = False
        state['errors'].append({
            'stage': 'check_legacy',
            'error': str(e),
            'traceback': traceback.format_exc()
        })
    
    return state


async def validation_node(state: OrchestratorState, db_pool) -> OrchestratorState:
    """
    Node 1: Validate PDF and extract metadata.
    
    Uses: ValidationService (simple service, not agent)
    """
    document_id = state['document_id']
    filepath = state['filepath']
    
    logger.info(f"[{document_id}] Starting validation: {filepath}")
    
    # Register event: started
    start_time = time.time()
    await _persist_event(
        document_id=document_id,
        stage='validation',
        status='started',
        metadata={'filepath': filepath},
        db_pool=db_pool
    )
    
    state['current_stage'] = 'validation'
    
    try:
        # TODO: Call ValidationService here
        # For now, simple validation
        import os
        if not os.path.exists(filepath):
            raise FileNotFoundError(f"File not found: {filepath}")
        
        if not filepath.endswith('.pdf'):
            raise ValueError(f"Not a PDF file: {filepath}")
        
        # Get file size
        file_size = os.path.getsize(filepath)
        
        duration = time.time() - start_time
        
        # Store result
        validation_result = {
            'valid': True,
            'filepath': filepath,
            'file_size': file_size,
            'duration': duration
        }
        
        state['new_data']['validation'] = NewData(
            stage=PipelineStage.VALIDATION,
            data=validation_result,
            timestamp=datetime.utcnow(),
            agent_used='ValidationService'
        ).dict()
        
        state['pipeline_context']['validation'] = validation_result
        
        # Register event: completed
        await _persist_event(
            document_id=document_id,
            stage='validation',
            status='completed',
            duration=duration,
            metadata={'file_size': file_size, 'valid': True},
            db_pool=db_pool
        )
        
        logger.info(f"[{document_id}] ✅ Validation completed: {file_size} bytes")
        
    except Exception as e:
        duration = time.time() - start_time
        error_msg = str(e)
        
        state['errors'].append({
            'stage': 'validation',
            'error': error_msg,
            'traceback': traceback.format_exc()
        })
        
        # Register event: error
        await _persist_event(
            document_id=document_id,
            stage='validation',
            status='error',
            duration=duration,
            error_type=type(e).__name__,
            error_message=error_msg,
            error_detail={'traceback': traceback.format_exc()},
            db_pool=db_pool
        )
        
        logger.error(f"[{document_id}] ❌ Validation failed: {e}")
        raise
    
    return state


async def ocr_node(state: OrchestratorState, db_pool) -> OrchestratorState:
    """
    Node 2: Extract text from PDF using OCR.
    
    Uses: OCRService with OCRmyPDF (preferred) or Tika (fallback)
    """
    document_id = state['document_id']
    filepath = state['filepath']
    filename = state['filename']
    
    logger.info(f"[{document_id}] Starting OCR: {filename}")
    
    start_time = time.time()
    await _persist_event(
        document_id=document_id,
        stage='ocr',
        status='started',
        metadata={'filepath': filepath, 'filename': filename},
        db_pool=db_pool
    )
    
    state['current_stage'] = 'ocr'
    
    try:
        # Import OCR services
        from ocr_service_ocrmypdf import OCRServiceOCRmyPDF
        from ocr_service import analyze_pdf
        
        # Analyze PDF to determine strategy
        pdf_info = analyze_pdf(filepath)
        
        # Use OCRmyPDF for scanned PDFs or OCRService for text PDFs
        if pdf_info['is_scanned'] or pdf_info['text_ratio'] < 0.5:
            logger.info(f"[{document_id}] Using OCRmyPDF (scanned PDF, text_ratio={pdf_info['text_ratio']:.2%})")
            ocr_service = OCRServiceOCRmyPDF()
            text = ocr_service.extract_text(filepath)
            engine = 'ocrmypdf'
        else:
            logger.info(f"[{document_id}] Using PyMuPDF (text PDF, text_ratio={pdf_info['text_ratio']:.2%})")
            # For text PDFs, use fast PyMuPDF extraction
            import fitz
            doc = fitz.open(filepath)
            text = ""
            for page in doc:
                text += page.get_text()
            doc.close()
            engine = 'pymupdf'
        
        duration = time.time() - start_time
        text_length = len(text)
        
        # Store result
        ocr_result = {
            'text': text,
            'pages': pdf_info['page_count'],
            'text_length': text_length,
            'duration': duration,
            'engine': engine,
            'is_scanned': pdf_info['is_scanned'],
            'text_ratio': pdf_info['text_ratio']
        }
        
        state['new_data']['ocr'] = NewData(
            stage=PipelineStage.OCR,
            data=ocr_result,
            timestamp=datetime.utcnow(),
            agent_used=f'OCRService ({engine})'
        ).dict()
        
        state['pipeline_context']['ocr'] = ocr_result
        
        # Decide where to store result (< 1MB in DB, > 1MB in filesystem)
        result_ref = None
        if text_length > 1_000_000:  # > 1MB
            # TODO: Save to filesystem
            result_ref = f"local-data/results/{document_id}/ocr_result.json"
            logger.info(f"[{document_id}] OCR result large ({text_length} bytes), reference: {result_ref}")
        else:
            # Store in pipeline_results table
            await db_pool.execute(
                """
                INSERT INTO pipeline_results (document_id, stage, result_data, result_size_bytes, result_checksum)
                VALUES ($1, 'ocr', $2, $3, $4)
                ON CONFLICT (document_id, stage) DO UPDATE 
                SET result_data = EXCLUDED.result_data,
                    result_size_bytes = EXCLUDED.result_size_bytes,
                    result_checksum = EXCLUDED.result_checksum,
                    created_at = NOW()
                """,
                document_id,
                ocr_result,
                text_length,
                None  # TODO: calculate SHA256 checksum
            )
        
        # Register event: completed
        await _persist_event(
            document_id=document_id,
            stage='ocr',
            status='completed',
            duration=duration,
            metadata={
                'text_length': text_length,
                'pages': pdf_info['page_count'],
                'engine': engine,
                'is_scanned': pdf_info['is_scanned']
            },
            result_ref=result_ref,
            result_size_bytes=text_length,
            db_pool=db_pool
        )
        
        logger.info(f"[{document_id}] ✅ OCR completed: {text_length} chars, {duration:.2f}s, engine={engine}")
        
        # Decision: Skip insights if OCR took too long
        if duration > 300:  # > 5 minutes
            logger.warning(f"[{document_id}] OCR took {duration:.2f}s, marking skip_insights=True")
            state['skip_insights'] = True
        
    except Exception as e:
        duration = time.time() - start_time
        error_msg = str(e)
        
        state['errors'].append({
            'stage': 'ocr',
            'error': error_msg,
            'traceback': traceback.format_exc()
        })
        
        await _persist_event(
            document_id=document_id,
            stage='ocr',
            status='error',
            duration=duration,
            error_type=type(e).__name__,
            error_message=error_msg,
            error_detail={'traceback': traceback.format_exc()},
            db_pool=db_pool
        )
        
        logger.error(f"[{document_id}] ❌ OCR failed: {e}")
        raise
    
    return state


async def legacy_adapter_node(state: OrchestratorState, db_pool, legacy_repo: LegacyDataRepository) -> OrchestratorState:
    """
    Node: Legacy Data Adapter
    
    Reads legacy data for current stage, validates against new data,
    merges according to strategy, and persists migration snapshot.
    
    This node runs AFTER each processing node if migration_mode=True.
    """
    if not state['migration_mode']:
        logger.debug(f"[{state['document_id']}] Not in migration mode, skipping legacy adapter")
        return state
    
    document_id = state['document_id']
    current_stage = state['current_stage']
    
    if not current_stage:
        logger.warning(f"[{document_id}] No current_stage set, cannot run legacy adapter")
        return state
    
    logger.info(f"[{document_id}] Running legacy adapter for stage: {current_stage}")
    
    try:
        # 1. Get legacy data for this stage
        legacy_data = await legacy_repo.get_legacy_data(
            document_id=UUID(document_id) if len(document_id) == 36 else document_id,
            stage=PipelineStage(current_stage)
        )
        
        state['legacy_data'][current_stage] = legacy_data.dict() if legacy_data else None
        
        # 2. Get new data for this stage
        new_data_dict = state['new_data'].get(current_stage)
        if not new_data_dict:
            logger.warning(f"[{document_id}] No new data for stage {current_stage}")
            return state
        
        new_data = NewData(**new_data_dict)
        
        # 3. Validate (compare legacy vs new)
        validation_result = await legacy_repo.validate_migration(
            document_id=UUID(document_id) if len(document_id) == 36 else document_id,
            stage=PipelineStage(current_stage),
            legacy_data=legacy_data,
            new_data=new_data
        )
        
        state['validation_results'][current_stage] = validation_result.dict()
        
        logger.info(
            f"[{document_id}] Validation for {current_stage}: "
            f"status={validation_result.status.value}, "
            f"similarity={validation_result.similarity_score}"
        )
        
        # 4. Merge data according to strategy
        merged_data = MergedData(
            stage=PipelineStage(current_stage),
            data=new_data.data,  # Default: use new data
            sources=['orchestrator'],
            merge_strategy=validation_result.recommendation,
            metadata={
                'validation_status': validation_result.status.value,
                'similarity': validation_result.similarity_score
            }
        )
        
        # If legacy exists and similarity is high, note both sources
        if legacy_data and legacy_data.exists and validation_result.similarity_score and validation_result.similarity_score > 0.9:
            merged_data.sources = ['legacy', 'orchestrator']
            merged_data.metadata['legacy_validated'] = True
        
        state['merged_data'][current_stage] = merged_data.dict()
        
        # 5. Persist migration snapshot
        snapshot_id = await legacy_repo.save_migration_snapshot(
            document_id=UUID(document_id) if len(document_id) == 36 else document_id,
            stage=PipelineStage(current_stage),
            legacy_data=legacy_data,
            new_data=new_data,
            validation_result=validation_result,
            merged_data=merged_data
        )
        
        logger.info(f"[{document_id}] ✅ Legacy adapter completed for {current_stage} (snapshot_id={snapshot_id})")
        
    except Exception as e:
        logger.error(f"[{document_id}] Legacy adapter failed for {current_stage}: {e}", exc_info=True)
        state['errors'].append({
            'stage': f'legacy_adapter_{current_stage}',
            'error': str(e),
            'traceback': traceback.format_exc()
        })
        # Don't raise - legacy adapter failure shouldn't stop pipeline
    
    return state


async def segmentation_node(state: OrchestratorState, db_pool) -> OrchestratorState:
    """
    Node 3: Segment document into news articles.
    
    Uses: NewsSegmentationAgent (LLM-based agent)
    """
    document_id = state['document_id']
    
    # Get OCR text from pipeline context
    ocr_data = state['pipeline_context'].get('ocr')
    if not ocr_data:
        raise ValueError("No OCR data available for segmentation")
    
    text = ocr_data['text']
    
    logger.info(f"[{document_id}] Starting segmentation")
    
    start_time = time.time()
    await _persist_event(
        document_id=document_id,
        stage='segmentation',
        status='started',
        metadata={'text_length': len(text)},
        db_pool=db_pool
    )
    
    state['current_stage'] = 'segmentation'
    
    try:
        # Import and use NewsSegmentationAgent
        from news_segmentation_agent import NewsSegmentationAgent
        
        agent = NewsSegmentationAgent(
            model=os.getenv("SEGMENTATION_LLM_MODEL", "llama3.2:1b"),
            temperature=0.0
        )
        
        # Segment document into articles
        articles = agent.segment_document(
            text=text,
            min_confidence=0.7,
            max_items=200,
            chunk_size=40000,
            overlap=5000
        )
        
        duration = time.time() - start_time
        
        # Store result
        segmentation_result = {
            'articles': articles,
            'count': len(articles),
            'avg_confidence': sum(a['confidence'] for a in articles) / len(articles) if articles else 0.0,
            'total_body_length': sum(a.get('body_length', 0) for a in articles),
            'duration': duration,
            'llm_model': agent.model
        }
        
        state['new_data']['segmentation'] = NewData(
            stage=PipelineStage.SEGMENTATION,
            data=segmentation_result,
            timestamp=datetime.utcnow(),
            agent_used=f'NewsSegmentationAgent ({agent.model})'
        ).dict()
        
        state['pipeline_context']['segmentation'] = segmentation_result
        
        # Decide where to store result (< 1MB in DB, > 1MB in filesystem)
        result_size = len(json.dumps(segmentation_result))
        result_ref = None
        
        if result_size > 1_000_000:  # > 1MB
            # TODO: Save to filesystem
            result_ref = f"local-data/results/{document_id}/segmentation_result.json"
            logger.info(f"[{document_id}] Segmentation result large ({result_size} bytes), reference: {result_ref}")
        else:
            # Store in pipeline_results table
            await db_pool.execute(
                """
                INSERT INTO pipeline_results (document_id, stage, result_data, result_size_bytes, result_checksum)
                VALUES ($1, 'segmentation', $2, $3, $4)
                ON CONFLICT (document_id, stage) DO UPDATE 
                SET result_data = EXCLUDED.result_data,
                    result_size_bytes = EXCLUDED.result_size_bytes,
                    result_checksum = EXCLUDED.result_checksum,
                    created_at = NOW()
                """,
                document_id,
                segmentation_result,
                result_size,
                None  # TODO: calculate SHA256 checksum
            )
        
        # Register event: completed
        await _persist_event(
            document_id=document_id,
            stage='segmentation',
            status='completed',
            duration=duration,
            metadata={
                'articles_count': len(articles),
                'avg_confidence': segmentation_result['avg_confidence'],
                'llm_model': agent.model
            },
            result_ref=result_ref,
            result_size_bytes=result_size,
            db_pool=db_pool
        )
        
        logger.info(f"[{document_id}] ✅ Segmentation completed: {len(articles)} articles, {duration:.2f}s")
        
    except Exception as e:
        duration = time.time() - start_time
        error_msg = str(e)
        
        state['errors'].append({
            'stage': 'segmentation',
            'error': error_msg,
            'traceback': traceback.format_exc()
        })
        
        await _persist_event(
            document_id=document_id,
            stage='segmentation',
            status='error',
            duration=duration,
            error_type=type(e).__name__,
            error_message=error_msg,
            error_detail={'traceback': traceback.format_exc()},
            db_pool=db_pool
        )
        
        logger.error(f"[{document_id}] ❌ Segmentation failed: {e}")
        raise
    
    return state


async def chunking_node(state: OrchestratorState, db_pool) -> OrchestratorState:
    """
    Node 5: Chunk articles into smaller pieces for indexing.
    
    Uses: RecursiveCharacterTextSplitter (LangChain)
    """
    document_id = state['document_id']
    
    logger.info(f"[{document_id}] Starting chunking")
    
    start_time = time.time()
    await _persist_event(
        document_id=document_id,
        stage='chunking',
        status='started',
        db_pool=db_pool
    )
    
    state['current_stage'] = 'chunking'
    
    try:
        # Get segmentation results
        segmentation_result = state['pipeline_context'].get('segmentation', {})
        articles = segmentation_result.get('articles', [])
        
        if not articles:
            raise ValueError("No articles found for chunking")
        
        # Use LangChain's RecursiveCharacterTextSplitter
        from langchain.text_splitter import RecursiveCharacterTextSplitter
        
        splitter = RecursiveCharacterTextSplitter(
            chunk_size=int(os.getenv('CHUNK_SIZE', '1000')),
            chunk_overlap=int(os.getenv('CHUNK_OVERLAP', '200')),
            separators=["\n\n", "\n", ".", " ", ""]
        )
        
        # Chunk each article
        chunks = []
        for article in articles:
            article_text = article.get('text', '')
            article_title = article.get('title', '')
            
            if not article_text:
                continue
            
            # Split into chunks
            article_chunks = splitter.split_text(article_text)
            
            for chunk_idx, chunk_text in enumerate(article_chunks):
                chunks.append({
                    'article_title': article_title,
                    'article_index': articles.index(article),
                    'chunk_index': chunk_idx,
                    'chunk_text': chunk_text,
                    'chunk_size': len(chunk_text),
                    'metadata': {
                        'title': article_title,
                        'confidence': article.get('confidence', 0.0),
                        'chunk_id': f"{document_id}_{articles.index(article)}_{chunk_idx}"
                    }
                })
        
        duration = time.time() - start_time
        
        # Store result
        chunking_result = {
            'chunks': chunks,
            'chunk_count': len(chunks),
            'article_count': len(articles),
            'avg_chunk_size': sum(c['chunk_size'] for c in chunks) / len(chunks) if chunks else 0,
            'duration': duration,
            'chunk_size': int(os.getenv('CHUNK_SIZE', '1000')),
            'chunk_overlap': int(os.getenv('CHUNK_OVERLAP', '200'))
        }
        
        state['new_data']['chunking'] = NewData(
            stage=PipelineStage.CHUNKING,
            data=chunking_result,
            timestamp=datetime.utcnow(),
            agent_used='RecursiveCharacterTextSplitter'
        ).dict()
        
        state['pipeline_context']['chunking'] = chunking_result
        
        # Decide where to store result
        result_size = len(json.dumps(chunking_result))
        result_ref = None
        
        if result_size > 1_000_000:  # > 1MB
            # TODO: Save to filesystem
            result_ref = f"local-data/results/{document_id}/chunking_result.json"
            logger.info(f"[{document_id}] Chunking result large ({result_size} bytes), reference: {result_ref}")
        else:
            # Store in pipeline_results table
            await db_pool.execute(
                """
                INSERT INTO pipeline_results (document_id, stage, result_data, result_size_bytes, result_checksum)
                VALUES ($1, 'chunking', $2, $3, $4)
                ON CONFLICT (document_id, stage) DO UPDATE 
                SET result_data = EXCLUDED.result_data,
                    result_size_bytes = EXCLUDED.result_size_bytes,
                    result_checksum = EXCLUDED.result_checksum,
                    created_at = NOW()
                """,
                document_id,
                chunking_result,
                result_size,
                None
            )
        
        # Register event: completed
        await _persist_event(
            document_id=document_id,
            stage='chunking',
            status='completed',
            duration=duration,
            metadata={
                'chunk_count': len(chunks),
                'article_count': len(articles),
                'avg_chunk_size': chunking_result['avg_chunk_size']
            },
            result_ref=result_ref,
            result_size_bytes=result_size,
            db_pool=db_pool
        )
        
        logger.info(f"[{document_id}] ✅ Chunking completed: {len(chunks)} chunks from {len(articles)} articles, {duration:.2f}s")
        
    except Exception as e:
        duration = time.time() - start_time
        error_msg = str(e)
        
        state['errors'].append({
            'stage': 'chunking',
            'error': error_msg,
            'traceback': traceback.format_exc()
        })
        
        await _persist_event(
            document_id=document_id,
            stage='chunking',
            status='error',
            duration=duration,
            error_type=type(e).__name__,
            error_message=error_msg,
            error_detail={'traceback': traceback.format_exc()},
            db_pool=db_pool
        )
        
        logger.error(f"[{document_id}] ❌ Chunking failed: {e}")
        raise
    
    return state


async def indexing_node(state: OrchestratorState, db_pool) -> OrchestratorState:
    """
    Node 6: Index chunks in Qdrant vector database.
    
    Uses: QdrantConnector + HuggingFaceEmbeddings
    """
    document_id = state['document_id']
    
    logger.info(f"[{document_id}] Starting indexing")
    
    start_time = time.time()
    await _persist_event(
        document_id=document_id,
        stage='indexing',
        status='started',
        db_pool=db_pool
    )
    
    state['current_stage'] = 'indexing'
    
    try:
        # Get chunking results
        chunking_result = state['pipeline_context'].get('chunking', {})
        chunks = chunking_result.get('chunks', [])
        
        if not chunks:
            raise ValueError("No chunks found for indexing")
        
        # Import Qdrant connector
        from qdrant_connector import QdrantConnector
        
        # Initialize connector
        qdrant = QdrantConnector(
            host=os.getenv('QDRANT_HOST', 'qdrant'),
            port=int(os.getenv('QDRANT_PORT', '6333')),
            collection_name=os.getenv('QDRANT_COLLECTION_NAME', 'news_collection')
        )
        
        # Index chunks
        indexed_count = 0
        for chunk in chunks:
            chunk_id = chunk['metadata']['chunk_id']
            chunk_text = chunk['chunk_text']
            chunk_metadata = {
                **chunk['metadata'],
                'document_id': document_id,
                'article_title': chunk['article_title'],
                'article_index': chunk['article_index'],
                'chunk_index': chunk['chunk_index']
            }
            
            # Add to Qdrant
            try:
                qdrant.add_texts(
                    texts=[chunk_text],
                    metadatas=[chunk_metadata],
                    ids=[chunk_id]
                )
                indexed_count += 1
            except Exception as chunk_error:
                logger.warning(f"[{document_id}] Failed to index chunk {chunk_id}: {chunk_error}")
        
        duration = time.time() - start_time
        
        # Store result
        indexing_result = {
            'indexed_count': indexed_count,
            'total_chunks': len(chunks),
            'success_rate': indexed_count / len(chunks) if chunks else 0.0,
            'duration': duration,
            'collection_name': qdrant.collection_name
        }
        
        state['new_data']['indexing'] = NewData(
            stage=PipelineStage.INDEXING,
            data=indexing_result,
            timestamp=datetime.utcnow(),
            agent_used='QdrantConnector'
        ).dict()
        
        state['pipeline_context']['indexing'] = indexing_result
        
        # Store in pipeline_results table
        result_size = len(json.dumps(indexing_result))
        await db_pool.execute(
            """
            INSERT INTO pipeline_results (document_id, stage, result_data, result_size_bytes, result_checksum)
            VALUES ($1, 'indexing', $2, $3, $4)
            ON CONFLICT (document_id, stage) DO UPDATE 
            SET result_data = EXCLUDED.result_data,
                result_size_bytes = EXCLUDED.result_size_bytes,
                result_checksum = EXCLUDED.result_checksum,
                created_at = NOW()
            """,
            document_id,
            indexing_result,
            result_size,
            None
        )
        
        # Register event: completed
        await _persist_event(
            document_id=document_id,
            stage='indexing',
            status='completed',
            duration=duration,
            metadata={
                'indexed_count': indexed_count,
                'success_rate': indexing_result['success_rate']
            },
            result_size_bytes=result_size,
            db_pool=db_pool
        )
        
        logger.info(
            f"[{document_id}] ✅ Indexing completed: {indexed_count}/{len(chunks)} chunks indexed, "
            f"success_rate={indexing_result['success_rate']:.2%}, {duration:.2f}s"
        )
        
    except Exception as e:
        duration = time.time() - start_time
        error_msg = str(e)
        
        state['errors'].append({
            'stage': 'indexing',
            'error': error_msg,
            'traceback': traceback.format_exc()
        })
        
        await _persist_event(
            document_id=document_id,
            stage='indexing',
            status='error',
            duration=duration,
            error_type=type(e).__name__,
            error_message=error_msg,
            error_detail={'traceback': traceback.format_exc()},
            db_pool=db_pool
        )
        
        logger.error(f"[{document_id}] ❌ Indexing failed: {e}")
        raise
    
    return state


async def insights_node(state: OrchestratorState, db_pool) -> OrchestratorState:
    """
    Node 7: Generate insights for each article using LLM.
    
    Uses: InsightsGraph (LangGraph workflow with extraction + analysis)
    """
    document_id = state['document_id']
    
    logger.info(f"[{document_id}] Starting insights generation")
    
    start_time = time.time()
    await _persist_event(
        document_id=document_id,
        stage='insights',
        status='started',
        db_pool=db_pool
    )
    
    state['current_stage'] = 'insights'
    
    try:
        # Check if insights should be skipped
        if state.get('skip_insights', False):
            logger.warning(f"[{document_id}] Skipping insights generation (skip_insights=True)")
            duration = time.time() - start_time
            
            # Register event: skipped
            await _persist_event(
                document_id=document_id,
                stage='insights',
                status='skipped',
                duration=duration,
                metadata={'reason': 'skip_insights flag set'},
                db_pool=db_pool
            )
            
            return state
        
        # Get segmentation results
        segmentation_result = state['pipeline_context'].get('segmentation', {})
        articles = segmentation_result.get('articles', [])
        
        if not articles:
            raise ValueError("No articles found for insights generation")
        
        # Import InsightsGraph
        from adapters.driven.llm.graphs.insights_graph import InsightsGraph, InsightState
        
        # Initialize insights graph
        insights_graph = InsightsGraph()
        
        # Generate insights for each article
        insights_results = []
        success_count = 0
        
        for article in articles[:10]:  # Limit to 10 articles for now (TODO: configurable)
            article_title = article.get('title', '')
            article_text = article.get('text', '')
            
            if not article_text:
                continue
            
            try:
                # Prepare state for insights graph
                insight_state: InsightState = {
                    'news_item_id': f"{document_id}_{articles.index(article)}",
                    'document_id': document_id,
                    'context': article_text,
                    'title': article_title,
                    'ocr_validated': True,
                    'ocr_validation_reason': None,
                    'extracted_data': None,
                    'extraction_tokens': 0,
                    'web_enrichment': None,
                    'enrichment_tokens': 0,
                    'analysis': None,
                    'analysis_tokens': 0,
                    'extraction_valid': False,
                    'analysis_valid': False,
                    'extraction_attempts': 0,
                    'analysis_attempts': 0,
                    'max_attempts': 3,
                    'provider_used': None,
                    'model_used': None,
                    'full_text': None,
                    'success': False,
                    'error': None,
                    'error_step': None
                }
                
                # Run insights workflow
                result = await insights_graph.run(insight_state)
                
                if result.get('success'):
                    insights_results.append({
                        'article_title': article_title,
                        'article_index': articles.index(article),
                        'extracted_data': result.get('extracted_data'),
                        'analysis': result.get('analysis'),
                        'full_text': result.get('full_text'),
                        'provider_used': result.get('provider_used'),
                        'model_used': result.get('model_used')
                    })
                    success_count += 1
                else:
                    logger.warning(
                        f"[{document_id}] Insights generation failed for article {articles.index(article)}: "
                        f"{result.get('error')}"
                    )
            
            except Exception as article_error:
                logger.warning(
                    f"[{document_id}] Failed to generate insights for article {articles.index(article)}: "
                    f"{article_error}"
                )
        
        duration = time.time() - start_time
        
        # Store result
        insights_result = {
            'insights': insights_results,
            'success_count': success_count,
            'total_articles': len(articles[:10]),
            'success_rate': success_count / len(articles[:10]) if articles else 0.0,
            'duration': duration
        }
        
        state['new_data']['insights'] = NewData(
            stage=PipelineStage.INSIGHTS,
            data=insights_result,
            timestamp=datetime.utcnow(),
            agent_used='InsightsGraph'
        ).dict()
        
        state['pipeline_context']['insights'] = insights_result
        
        # Decide where to store result
        result_size = len(json.dumps(insights_result))
        result_ref = None
        
        if result_size > 1_000_000:  # > 1MB
            # TODO: Save to filesystem
            result_ref = f"local-data/results/{document_id}/insights_result.json"
            logger.info(f"[{document_id}] Insights result large ({result_size} bytes), reference: {result_ref}")
        else:
            # Store in pipeline_results table
            await db_pool.execute(
                """
                INSERT INTO pipeline_results (document_id, stage, result_data, result_size_bytes, result_checksum)
                VALUES ($1, 'insights', $2, $3, $4)
                ON CONFLICT (document_id, stage) DO UPDATE 
                SET result_data = EXCLUDED.result_data,
                    result_size_bytes = EXCLUDED.result_size_bytes,
                    result_checksum = EXCLUDED.result_checksum,
                    created_at = NOW()
                """,
                document_id,
                insights_result,
                result_size,
                None
            )
        
        # Register event: completed
        await _persist_event(
            document_id=document_id,
            stage='insights',
            status='completed',
            duration=duration,
            metadata={
                'success_count': success_count,
                'total_articles': len(articles[:10]),
                'success_rate': insights_result['success_rate']
            },
            result_ref=result_ref,
            result_size_bytes=result_size,
            db_pool=db_pool
        )
        
        logger.info(
            f"[{document_id}] ✅ Insights generation completed: {success_count}/{len(articles[:10])} articles, "
            f"success_rate={insights_result['success_rate']:.2%}, {duration:.2f}s"
        )
        
    except Exception as e:
        duration = time.time() - start_time
        error_msg = str(e)
        
        state['errors'].append({
            'stage': 'insights',
            'error': error_msg,
            'traceback': traceback.format_exc()
        })
        
        await _persist_event(
            document_id=document_id,
            stage='insights',
            status='error',
            duration=duration,
            error_type=type(e).__name__,
            error_message=error_msg,
            error_detail={'traceback': traceback.format_exc()},
            db_pool=db_pool
        )
        
        logger.error(f"[{document_id}] ❌ Insights generation failed: {e}")
        raise
    
    return state


# ============================================================================
# Orchestrator Agent Builder
# ============================================================================

def build_orchestrator_workflow(db_pool, legacy_repo: LegacyDataRepository) -> StateGraph:
    """
    Build the complete Pipeline Orchestrator Agent workflow.
    
    Args:
        db_pool: AsyncPG connection pool for DB operations
        legacy_repo: Repository for legacy data operations
    
    Returns:
        Compiled LangGraph workflow with legacy validation at each stage
    """
    workflow = StateGraph(OrchestratorState)
    
    # Add nodes (processing + legacy adapter after each)
    workflow.add_node("check_legacy", lambda state: check_if_legacy_node(state, db_pool))
    workflow.add_node("validation", lambda state: validation_node(state, db_pool))
    workflow.add_node("legacy_adapter_validation", lambda state: legacy_adapter_node(state, db_pool, legacy_repo))
    workflow.add_node("ocr", lambda state: ocr_node(state, db_pool))
    workflow.add_node("legacy_adapter_ocr", lambda state: legacy_adapter_node(state, db_pool, legacy_repo))
    workflow.add_node("segmentation", lambda state: segmentation_node(state, db_pool))
    workflow.add_node("legacy_adapter_segmentation", lambda state: legacy_adapter_node(state, db_pool, legacy_repo))
    workflow.add_node("chunking", lambda state: chunking_node(state, db_pool))
    workflow.add_node("legacy_adapter_chunking", lambda state: legacy_adapter_node(state, db_pool, legacy_repo))
    workflow.add_node("indexing", lambda state: indexing_node(state, db_pool))
    workflow.add_node("legacy_adapter_indexing", lambda state: legacy_adapter_node(state, db_pool, legacy_repo))
    workflow.add_node("insights", lambda state: insights_node(state, db_pool))
    workflow.add_node("legacy_adapter_insights", lambda state: legacy_adapter_node(state, db_pool, legacy_repo))
    
    # Define flow with legacy validation after each stage
    workflow.set_entry_point("check_legacy")
    
    # Flow: check → validation → [legacy adapter] → ocr → [legacy adapter] → segmentation → [legacy adapter] → END
    workflow.add_edge("check_legacy", "validation")
    
    # Conditional: Skip legacy adapter if not in migration mode
    def should_run_legacy_adapter(state: OrchestratorState) -> str:
        return "legacy_adapter_validation" if state.get('migration_mode') else "ocr"
    
    workflow.add_conditional_edges(
        "validation",
        should_run_legacy_adapter,
        {
            "legacy_adapter_validation": "legacy_adapter_validation",
            "ocr": "ocr"
        }
    )
    
    workflow.add_edge("legacy_adapter_validation", "ocr")
    
    # OCR → legacy adapter
    def should_run_legacy_adapter_ocr(state: OrchestratorState) -> str:
        return "legacy_adapter_ocr" if state.get('migration_mode') else "segmentation"
    
    workflow.add_conditional_edges(
        "ocr",
        should_run_legacy_adapter_ocr,
        {
            "legacy_adapter_ocr": "legacy_adapter_ocr",
            "segmentation": "segmentation"
        }
    )
    
    workflow.add_edge("legacy_adapter_ocr", "segmentation")
    
    # Segmentation → legacy adapter → chunking
    def should_run_legacy_adapter_segmentation(state: OrchestratorState) -> str:
        return "legacy_adapter_segmentation" if state.get('migration_mode') else "chunking"
    
    workflow.add_conditional_edges(
        "segmentation",
        should_run_legacy_adapter_segmentation,
        {
            "legacy_adapter_segmentation": "legacy_adapter_segmentation",
            "chunking": "chunking"
        }
    )
    
    workflow.add_edge("legacy_adapter_segmentation", "chunking")
    
    # Chunking → legacy adapter → indexing
    def should_run_legacy_adapter_chunking(state: OrchestratorState) -> str:
        return "legacy_adapter_chunking" if state.get('migration_mode') else "indexing"
    
    workflow.add_conditional_edges(
        "chunking",
        should_run_legacy_adapter_chunking,
        {
            "legacy_adapter_chunking": "legacy_adapter_chunking",
            "indexing": "indexing"
        }
    )
    
    workflow.add_edge("legacy_adapter_chunking", "indexing")
    
    # Indexing → legacy adapter → insights
    def should_run_legacy_adapter_indexing(state: OrchestratorState) -> str:
        return "legacy_adapter_indexing" if state.get('migration_mode') else "insights"
    
    workflow.add_conditional_edges(
        "indexing",
        should_run_legacy_adapter_indexing,
        {
            "legacy_adapter_indexing": "legacy_adapter_indexing",
            "insights": "insights"
        }
    )
    
    workflow.add_edge("legacy_adapter_indexing", "insights")
    
    # Insights → legacy adapter → END
    def should_run_legacy_adapter_insights(state: OrchestratorState) -> str:
        return "legacy_adapter_insights" if state.get('migration_mode') else "end"
    
    workflow.add_conditional_edges(
        "insights",
        should_run_legacy_adapter_insights,
        {
            "legacy_adapter_insights": "legacy_adapter_insights",
            "end": END
        }
    )
    
    workflow.add_edge("legacy_adapter_insights", END)
    
    # Compile with checkpointing for recovery
    # TODO: Use persistent SQLite checkpoint for production
    # from langgraph.checkpoint.sqlite import SqliteSaver
    # memory = SqliteSaver.from_conn_string("checkpoints.db")
    # return workflow.compile(checkpointer=memory)
    
    return workflow.compile()


# ============================================================================
# Main Orchestrator Class
# ============================================================================

class PipelineOrchestratorAgent:
    """
    Main Pipeline Orchestrator Agent.
    
    Manages the entire document processing pipeline with:
    - Legacy validation
    - Observability
    - Recovery
    - Intelligent decisions
    """
    
    def __init__(self, db_pool):
        self.db_pool = db_pool
        self.legacy_repo = LegacyDataRepository(db_pool)
        self.workflow = build_orchestrator_workflow(db_pool, self.legacy_repo)
    
    async def process_document(
        self,
        document_id: str,
        filename: str,
        filepath: str
    ) -> Dict[str, Any]:
        """
        Process a complete document through the pipeline.
        
        Args:
            document_id: Document UUID/ID
            filename: Original filename
            filepath: Path to PDF file
        
        Returns:
            Final state with results
        """
        logger.info(f"🚀 Starting orchestrator for document: {document_id} ({filename})")
        
        # Initialize state
        initial_state: OrchestratorState = {
            'document_id': document_id,
            'filename': filename,
            'filepath': filepath,
            'metadata': {},
            'pipeline_context': {},
            'current_stage': None,
            'migration_mode': False,
            'legacy_data': {},
            'new_data': {},
            'validation_results': {},
            'merged_data': {},
            'events': [],
            'errors': [],
            'skip_insights': False,
            'retry_ocr_with_tika': False
        }
        
        try:
            # Execute workflow
            final_state = await self.workflow.ainvoke(initial_state)
            
            logger.info(f"✅ Orchestrator completed for document: {document_id}")
            
            return {
                'success': True,
                'document_id': document_id,
                'final_state': final_state,
                'errors': final_state.get('errors', [])
            }
        
        except Exception as e:
            logger.error(f"❌ Orchestrator failed for document {document_id}: {e}", exc_info=True)
            
            return {
                'success': False,
                'document_id': document_id,
                'error': str(e),
                'traceback': traceback.format_exc()
            }


# ============================================================================
# Factory Function
# ============================================================================

def create_orchestrator_agent(db_pool) -> PipelineOrchestratorAgent:
    """
    Factory function to create orchestrator agent instance.
    
    Usage:
        agent = create_orchestrator_agent(db_pool)
        result = await agent.process_document(doc_id, filename, filepath)
    """
    return PipelineOrchestratorAgent(db_pool)
