"""
Structured Insight Parser - Extracts structured data from insights for knowledge graph.

This allows us to parse the LLM-generated insights into structured entities
that can be used for graph analysis, filtering, and knowledge network building.
"""

import re
import logging
from dataclasses import dataclass, field
from typing import List, Optional, Dict
from datetime import datetime

logger = logging.getLogger(__name__)


@dataclass
class InsightMetadata:
    """Metadata extracted from insight."""
    date: Optional[str] = None
    location: Optional[str] = None
    source: Optional[str] = None
    author: Optional[str] = None
    publication: Optional[str] = None


@dataclass
class Actor:
    """Actor (person/organization) mentioned in news."""
    name: str
    role: Optional[str] = None
    action: Optional[str] = None
    entity_type: str = "person"  # person, organization, institution


@dataclass
class Fact:
    """Verifiable fact or event."""
    description: str
    date: Optional[str] = None
    location: Optional[str] = None


@dataclass
class Position:
    """Position or stance taken by an actor."""
    actor: str
    stance: str
    topic: Optional[str] = None


@dataclass
class StructuredInsight:
    """
    Structured representation of a news insight.
    
    This enables:
    - Knowledge graph construction
    - Temporal analysis
    - Actor network analysis
    - Theme tracking
    - Cross-document connections
    """
    # Raw insight text
    raw_text: str
    
    # Structured data
    metadata: InsightMetadata
    actors: List[Actor] = field(default_factory=list)
    facts: List[Fact] = field(default_factory=list)
    themes: List[str] = field(default_factory=list)
    positions: List[Position] = field(default_factory=list)
    connections: Optional[str] = None
    analysis: Optional[str] = None
    
    # For graph building
    def get_entities(self) -> List[Dict]:
        """Get all entities for knowledge graph."""
        entities = []
        
        # Add actors as nodes
        for actor in self.actors:
            entities.append({
                "type": "actor",
                "name": actor.name,
                "role": actor.role,
                "entity_type": actor.entity_type
            })
        
        # Add locations as nodes
        if self.metadata.location:
            entities.append({
                "type": "location",
                "name": self.metadata.location
            })
        
        # Add themes as nodes
        for theme in self.themes:
            entities.append({
                "type": "theme",
                "name": theme
            })
        
        return entities
    
    def get_relationships(self) -> List[Dict]:
        """Get relationships between entities for graph."""
        relationships = []
        
        # Actor -> Location
        if self.metadata.location:
            for actor in self.actors:
                relationships.append({
                    "from": actor.name,
                    "to": self.metadata.location,
                    "type": "LOCATED_IN"
                })
        
        # Actor -> Theme (based on facts)
        for actor in self.actors:
            for theme in self.themes:
                relationships.append({
                    "from": actor.name,
                    "to": theme,
                    "type": "RELATED_TO"
                })
        
        # Position relationships
        for position in self.positions:
            if position.topic:
                relationships.append({
                    "from": position.actor,
                    "to": position.topic,
                    "type": "POSITION_ON",
                    "stance": position.stance
                })
        
        return relationships


class InsightParser:
    """
    Parser for structured insights generated by InsightsChain.
    
    Extracts structured data from markdown-formatted insights.
    """
    
    @staticmethod
    def parse(insight_text: str) -> StructuredInsight:
        """
        Parse insight text into structured format.
        
        Args:
            insight_text: Raw insight text from LLM
        
        Returns:
            StructuredInsight with extracted data
        """
        # Extract sections using regex
        metadata = InsightParser._extract_metadata(insight_text)
        actors = InsightParser._extract_actors(insight_text)
        facts = InsightParser._extract_facts(insight_text)
        themes = InsightParser._extract_themes(insight_text)
        positions = InsightParser._extract_positions(insight_text)
        connections = InsightParser._extract_section(insight_text, "Connections")
        analysis = InsightParser._extract_section(insight_text, "Analysis")
        
        return StructuredInsight(
            raw_text=insight_text,
            metadata=metadata,
            actors=actors,
            facts=facts,
            themes=themes,
            positions=positions,
            connections=connections,
            analysis=analysis
        )
    
    @staticmethod
    def _extract_metadata(text: str) -> InsightMetadata:
        """Extract metadata section."""
        metadata = InsightMetadata()
        
        # Extract date
        date_match = re.search(r"Date:\s*(.+?)(?:\n|$)", text, re.IGNORECASE)
        if date_match:
            metadata.date = date_match.group(1).strip()
        
        # Extract location
        loc_match = re.search(r"Location:\s*(.+?)(?:\n|$)", text, re.IGNORECASE)
        if loc_match:
            metadata.location = loc_match.group(1).strip()
        
        # Extract source
        source_match = re.search(r"Source:\s*(.+?)(?:\n|$)", text, re.IGNORECASE)
        if source_match:
            metadata.source = source_match.group(1).strip()
        
        # Extract author
        author_match = re.search(r"Author:\s*(.+?)(?:\n|$)", text, re.IGNORECASE)
        if author_match:
            metadata.author = author_match.group(1).strip()
        
        return metadata
    
    @staticmethod
    def _extract_actors(text: str) -> List[Actor]:
        """Extract key actors section."""
        actors = []
        
        # Find Key Actors section
        section_match = re.search(
            r"##\s*Key Actors\s*\n(.*?)(?=##|\Z)",
            text,
            re.DOTALL | re.IGNORECASE
        )
        
        if section_match:
            actors_text = section_match.group(1)
            # Parse each line: - [Name]: [Role] - [Action]
            for line in actors_text.split("\n"):
                line = line.strip()
                if line.startswith("-"):
                    # Parse actor line
                    parts = line[1:].split(":", 1)
                    if len(parts) == 2:
                        name = parts[0].strip()
                        details = parts[1].strip()
                        
                        # Try to extract role and action
                        role_action = details.split(" - ", 1)
                        role = role_action[0].strip() if len(role_action) > 0 else None
                        action = role_action[1].strip() if len(role_action) > 1 else None
                        
                        actors.append(Actor(name=name, role=role, action=action))
        
        return actors
    
    @staticmethod
    def _extract_facts(text: str) -> List[Fact]:
        """Extract facts and events section."""
        facts = []
        
        section_match = re.search(
            r"##\s*Facts & Events\s*\n(.*?)(?=##|\Z)",
            text,
            re.DOTALL | re.IGNORECASE
        )
        
        if section_match:
            facts_text = section_match.group(1)
            for line in facts_text.split("\n"):
                line = line.strip()
                if line.startswith("-"):
                    fact_text = line[1:].strip()
                    facts.append(Fact(description=fact_text))
        
        return facts
    
    @staticmethod
    def _extract_themes(text: str) -> List[str]:
        """Extract themes section."""
        section_match = re.search(
            r"##\s*Themes\s*\n(.*?)(?=##|\Z)",
            text,
            re.DOTALL | re.IGNORECASE
        )
        
        if section_match:
            themes_text = section_match.group(1).strip()
            # Split by comma
            themes = [t.strip() for t in themes_text.split(",") if t.strip()]
            return themes
        
        return []
    
    @staticmethod
    def _extract_positions(text: str) -> List[Position]:
        """Extract positions section."""
        positions = []
        
        section_match = re.search(
            r"##\s*Positions\s*\n(.*?)(?=##|\Z)",
            text,
            re.DOTALL | re.IGNORECASE
        )
        
        if section_match:
            positions_text = section_match.group(1)
            for line in positions_text.split("\n"):
                line = line.strip()
                if line.startswith("-"):
                    # Parse: - [Actor]: [Stance]
                    parts = line[1:].split(":", 1)
                    if len(parts) == 2:
                        actor = parts[0].strip()
                        stance = parts[1].strip()
                        positions.append(Position(actor=actor, stance=stance))
        
        return positions
    
    @staticmethod
    def _extract_section(text: str, section_name: str) -> Optional[str]:
        """Extract a generic text section."""
        section_match = re.search(
            rf"##\s*{section_name}\s*\n(.*?)(?=##|\Z)",
            text,
            re.DOTALL | re.IGNORECASE
        )
        
        if section_match:
            return section_match.group(1).strip()
        
        return None


# Convenience function
def parse_insight(insight_text: str) -> StructuredInsight:
    """Parse insight text into structured format."""
    return InsightParser.parse(insight_text)
