"""
Pydantic Models for Legacy Migration System

These models provide validation and type safety for the migration process
from Event-Driven architecture to Orchestrator Agent.

Related: REQ-027_ORCHESTRATOR_MIGRATION.md, Migration 021
Date: 2026-04-10
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional, List, Dict, Any, Literal
from uuid import UUID

from pydantic import BaseModel, Field, validator, root_validator


# ============================================================================
# Enums
# ============================================================================

class PipelineStage(str, Enum):
    """Pipeline stages for migration tracking"""
    UPLOAD = "upload"
    VALIDATION = "validation"
    OCR = "ocr"
    OCR_VALIDATION = "ocr_validation"
    SEGMENTATION = "segmentation"
    CHUNKING = "chunking"
    INDEXING = "indexing"
    INSIGHTS = "insights"
    INDEXING_INSIGHTS = "indexing_insights"


class ValidationStatus(str, Enum):
    """Status of legacy vs new data validation"""
    PENDING = "pending"
    MATCH = "match"
    MISMATCH = "mismatch"
    CONFLICT = "conflict"
    NO_LEGACY = "no_legacy"


class MergeStrategy(str, Enum):
    """Strategy for merging legacy and new data"""
    KEEP_NEW = "keep_new"
    KEEP_LEGACY = "keep_legacy"
    MERGE_BOTH = "merge_both"
    MANUAL_REVIEW = "manual_review"


class MigrationStatus(str, Enum):
    """Overall migration status for a document"""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    VALIDATED = "validated"
    COMPLETED = "completed"


class DataSource(str, Enum):
    """Source of pipeline data"""
    LEGACY = "legacy"
    ORCHESTRATOR = "orchestrator"


# ============================================================================
# Core Models
# ============================================================================

class LegacyData(BaseModel):
    """
    Data from legacy Event-Driven pipeline.
    Snapshot of old data for a specific stage.
    """
    stage: PipelineStage
    exists: bool = Field(..., description="Whether legacy data exists for this stage")
    data: Dict[str, Any] = Field(default_factory=dict, description="Legacy data snapshot")
    timestamp: Optional[datetime] = Field(None, description="When legacy data was created")
    source_table: Optional[str] = Field(None, description="Source table (document_status, news_items, etc.)")
    
    class Config:
        use_enum_values = True


class NewData(BaseModel):
    """
    Data from new Orchestrator Agent pipeline.
    Fresh data generated by orchestrator.
    """
    stage: PipelineStage
    data: Dict[str, Any] = Field(..., description="New data from orchestrator")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When new data was created")
    agent_used: str = Field(..., description="Agent/Service that generated this data")
    
    class Config:
        use_enum_values = True


class ValidationResult(BaseModel):
    """
    Result of comparing legacy vs new data.
    Includes similarity score and differences.
    """
    stage: PipelineStage
    status: ValidationStatus
    similarity_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Similarity score 0.0-1.0")
    differences: List[str] = Field(default_factory=list, description="List of differences found")
    recommendation: MergeStrategy = Field(..., description="Recommended merge strategy")
    details: Dict[str, Any] = Field(default_factory=dict, description="Additional validation details")
    
    @validator('similarity_score')
    def validate_similarity_for_match(cls, v, values):
        """Enforce that 'match' status requires high similarity"""
        status = values.get('status')
        if status == ValidationStatus.MATCH:
            if v is None or v < 0.95:
                raise ValueError(f"Match status requires similarity >= 0.95, got {v}")
        return v
    
    @root_validator(skip_on_failure=True)
    def validate_no_legacy_status(cls, values):
        """Validate that no_legacy status has no similarity"""
        status = values.get('status')
        similarity = values.get('similarity_score')
        
        if status == ValidationStatus.NO_LEGACY and similarity is not None:
            raise ValueError("no_legacy status should not have similarity score")
        
        return values
    
    class Config:
        use_enum_values = True


class MergedData(BaseModel):
    """
    Final data after merging legacy and new.
    Result of applying merge strategy.
    """
    stage: PipelineStage
    data: Dict[str, Any] = Field(..., description="Final merged data")
    sources: List[Literal["legacy", "orchestrator"]] = Field(..., description="Sources used in merge")
    merge_strategy: MergeStrategy
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata about merge process")
    conflicts_resolved: List[str] = Field(default_factory=list, description="Conflicts that were resolved")
    
    @validator('sources')
    def validate_sources_not_empty(cls, v):
        """Ensure at least one source"""
        if not v:
            raise ValueError("sources cannot be empty")
        return v
    
    class Config:
        use_enum_values = True


# ============================================================================
# Migration Tracking Models
# ============================================================================

class MigrationTrackingRecord(BaseModel):
    """
    Full migration tracking record for a document stage.
    Corresponds to migration_tracking table.
    """
    id: Optional[int] = None
    document_id: UUID
    stage: PipelineStage
    
    # Legacy data
    legacy_exists: bool = False
    legacy_data: Optional[Dict[str, Any]] = None
    legacy_timestamp: Optional[datetime] = None
    legacy_source_table: Optional[str] = None
    
    # New data
    new_data: Optional[Dict[str, Any]] = None
    new_timestamp: Optional[datetime] = None
    
    # Validation
    validation_status: ValidationStatus = ValidationStatus.PENDING
    validation_result: Optional[Dict[str, Any]] = None
    similarity_score: Optional[float] = Field(None, ge=0.0, le=1.0)
    
    # Merge
    merged_data: Optional[Dict[str, Any]] = None
    merge_strategy: Optional[MergeStrategy] = None
    
    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    validated_at: Optional[datetime] = None
    migrated_at: Optional[datetime] = None
    
    class Config:
        use_enum_values = True
        orm_mode = True


class MigrationProgress(BaseModel):
    """
    Migration progress for a single stage.
    Corresponds to migration_progress view.
    """
    stage: PipelineStage
    total_documents: int
    validated_match: int = 0
    validated_mismatch: int = 0
    conflicts: int = 0
    no_legacy_data: int = 0
    migrated: int = 0
    percent_migrated: float = Field(0.0, ge=0.0, le=100.0)
    avg_similarity: Optional[float] = Field(None, ge=0.0, le=1.0)
    first_migration_start: Optional[datetime] = None
    last_migration_complete: Optional[datetime] = None
    
    class Config:
        use_enum_values = True


class GlobalMigrationProgress(BaseModel):
    """
    Overall migration progress across all stages.
    """
    total_documents: int
    total_migrated: int
    percent_complete: float = Field(..., ge=0.0, le=100.0)
    by_stage: Dict[str, MigrationProgress]
    total_conflicts: int
    cleanup_ready: bool = Field(False, description="True when 100% migrated")
    estimated_completion: Optional[datetime] = None
    
    @validator('cleanup_ready')
    def set_cleanup_ready(cls, v, values):
        """Auto-set cleanup_ready when 100% complete"""
        percent = values.get('percent_complete', 0.0)
        return percent >= 100.0
    
    class Config:
        use_enum_values = True


# ============================================================================
# Document Models
# ============================================================================

class DocumentMetadata(BaseModel):
    """
    Metadata extracted from document filename.
    Pattern: {sha8}_{DD-MM-YY}-{Newspaper}.pdf
    """
    sha8: str = Field(..., min_length=8, max_length=8, description="First 8 chars of SHA256")
    date: datetime = Field(..., description="Publication date")
    newspaper: str = Field(..., min_length=1, description="Newspaper name")
    is_valid: bool = Field(True, description="Whether parsing was successful")
    original_filename: Optional[str] = None
    
    @validator('sha8')
    def validate_sha8_hex(cls, v):
        """Validate that sha8 is valid hexadecimal"""
        try:
            int(v, 16)
        except ValueError:
            raise ValueError(f"sha8 must be valid hexadecimal, got: {v}")
        return v.lower()


class DocumentMigrationStatus(BaseModel):
    """
    Migration status for a complete document.
    Summary across all stages.
    """
    document_id: UUID
    filename: str
    publication_date: Optional[datetime] = None
    newspaper_name: Optional[str] = None
    
    # Migration status
    data_source: DataSource
    migration_status: MigrationStatus
    migrated_at: Optional[datetime] = None
    
    # Stage progress
    stages_tracked: int = 0
    stages_migrated: int = 0
    pending_stages: List[str] = Field(default_factory=list)
    
    @property
    def migration_percent(self) -> float:
        """Calculate migration percentage"""
        if self.stages_tracked == 0:
            return 0.0
        return (self.stages_migrated / self.stages_tracked) * 100.0
    
    class Config:
        use_enum_values = True


# ============================================================================
# Processing Log Models
# ============================================================================

class ProcessingLogEvent(BaseModel):
    """
    Single event in document processing log.
    Used for orchestrator observability.
    """
    id: Optional[int] = None
    document_id: UUID
    stage: PipelineStage
    status: Literal["started", "in_progress", "completed", "error", "skipped"]
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    duration_sec: Optional[float] = Field(None, ge=0.0)
    
    # Metadata
    metadata: Dict[str, Any] = Field(default_factory=dict)
    
    # Errors
    error_type: Optional[str] = None
    error_message: Optional[str] = None
    error_detail: Optional[Dict[str, Any]] = None
    
    # Result reference
    result_ref: Optional[str] = None
    result_size_bytes: Optional[int] = Field(None, ge=0)
    
    # Source
    event_source: Literal["orchestrator", "legacy"] = "orchestrator"
    
    class Config:
        use_enum_values = True
        orm_mode = True


# ============================================================================
# Helper Models for API Responses
# ============================================================================

class MigrationConflict(BaseModel):
    """
    Represents a conflict that requires manual review.
    """
    document_id: UUID
    stage: PipelineStage
    legacy_data: Dict[str, Any]
    new_data: Dict[str, Any]
    differences: List[str]
    similarity_score: float
    recommendation: str
    created_at: datetime


class MigrationStatistics(BaseModel):
    """
    Statistics for migration dashboard.
    """
    total_legacy_documents: int
    documents_migrated: int
    documents_in_progress: int
    documents_pending: int
    conflicts_to_resolve: int
    average_similarity: float
    stages_progress: Dict[str, float]  # stage -> percent
    estimated_time_remaining: Optional[str] = None


# ============================================================================
# Validation Helper Functions
# ============================================================================

def calculate_similarity(legacy: Dict[str, Any], new: Dict[str, Any], stage: PipelineStage) -> float:
    """
    Calculate similarity between legacy and new data.
    Strategy depends on stage.
    
    Returns: float 0.0 - 1.0
    """
    if stage == PipelineStage.OCR:
        # Text similarity (e.g., using difflib or Levenshtein)
        legacy_text = legacy.get('text', '')
        new_text = new.get('text', '')
        
        if not legacy_text or not new_text:
            return 0.0
        
        # Simple similarity (could use more sophisticated algorithm)
        from difflib import SequenceMatcher
        return SequenceMatcher(None, legacy_text, new_text).ratio()
    
    elif stage == PipelineStage.SEGMENTATION:
        # Article count similarity
        legacy_count = len(legacy.get('articles', []))
        new_count = len(new.get('articles', []))
        
        if legacy_count == 0 and new_count == 0:
            return 1.0
        
        max_count = max(legacy_count, new_count)
        if max_count == 0:
            return 1.0
        
        return 1.0 - abs(legacy_count - new_count) / max_count
    
    else:
        # Generic similarity (exact match check)
        return 1.0 if legacy == new else 0.5


def determine_merge_strategy(validation: ValidationResult) -> MergeStrategy:
    """
    Determine merge strategy based on validation result.
    """
    if validation.status == ValidationStatus.NO_LEGACY:
        return MergeStrategy.KEEP_NEW
    
    if validation.status == ValidationStatus.MATCH:
        return MergeStrategy.KEEP_NEW  # New is validated, use it
    
    if validation.status == ValidationStatus.CONFLICT:
        return MergeStrategy.MANUAL_REVIEW
    
    if validation.similarity_score and validation.similarity_score >= 0.95:
        return MergeStrategy.KEEP_NEW  # High similarity, trust new
    
    if validation.similarity_score and validation.similarity_score < 0.80:
        return MergeStrategy.MANUAL_REVIEW  # Low similarity, needs review
    
    return MergeStrategy.MERGE_BOTH  # Medium similarity, merge
